// @ts-nocheck — auto-generated barrel with lazy CJS re-exports
/**
 * gen-import.ts — AUTO-GENERATED, do not edit manually.
 * Regenerate: npx gen-import
 *
 * Value exports use lazy getters to prevent circular-dependency
 * errors when source files import from this barrel (CJS).
 */

export type { ScanContext } from './analysis/scan';
export type { BuildModuleGraphOptions } from './analysis/graph';
export type { BarrelAnalysisOptions, BarrelAnalysisResult, SafeExportSelection, SafeExportOptions } from './analysis/barrel';
export type { DepGraph } from './script';
export type { WatchOptions } from './core/watch';

export declare const isEager: typeof import('./analysis/scan').isEager;
export declare const strongerVia: typeof import('./analysis/scan').strongerVia;
export declare const classifyReference: typeof import('./analysis/scan').classifyReference;
export declare const strongerKind: typeof import('./analysis/scan').strongerKind;
export declare const scanFile: typeof import('./analysis/scan').scanFile;
export declare const createCanonicalizer: typeof import('./analysis/graph').createCanonicalizer;
export declare const buildModuleGraph: typeof import('./analysis/graph').buildModuleGraph;
export declare const contractBarrel: typeof import('./analysis/graph').contractBarrel;
export declare const withBarrelExports: typeof import('./analysis/graph').withBarrelExports;
export declare const consumersOf: typeof import('./analysis/graph').consumersOf;
export declare const INIT_EDGE_KINDS: typeof import('./analysis/graph').INIT_EDGE_KINDS;
export declare const tarjanScc: typeof import('./analysis/scc').tarjanScc;
export declare const topoOrder: typeof import('./analysis/scc').topoOrder;
export declare const cyclicSccs: typeof import('./analysis/scc').cyclicSccs;
export declare const shortestCycle: typeof import('./analysis/scc').shortestCycle;
export declare const cycleEdges: typeof import('./analysis/scc').cycleEdges;
export declare const condensation: typeof import('./analysis/scc').condensation;
export declare const buildRuntimeGraph: typeof import('./analysis/barrel').buildRuntimeGraph;
export declare const analyzeBarrel: typeof import('./analysis/barrel').analyzeBarrel;
export declare const analyzeBarrelGraph: typeof import('./analysis/barrel').analyzeBarrelGraph;
export declare const selectSafeExports: typeof import('./analysis/barrel').selectSafeExports;
export declare const describeEagerEdge: typeof import('./analysis/barrel').describeEagerEdge;
export declare const explainVia: typeof import('./analysis/diagnostics').explainVia;
export declare const collectCycleDiagnostics: typeof import('./analysis/diagnostics').collectCycleDiagnostics;
export declare const collectBarrelDiagnostics: typeof import('./analysis/diagnostics').collectBarrelDiagnostics;
export declare const countBySeverity: typeof import('./analysis/diagnostics').countBySeverity;
export declare const formatDiagnostics: typeof import('./analysis/diagnostics').formatDiagnostics;
export declare const SEVERITY_BY_CODE: typeof import('./analysis/diagnostics').SEVERITY_BY_CODE;
export declare const walk: typeof import('./script').walk;
export declare const detectModuleType: typeof import('./script').detectModuleType;
export declare const detectProjectLanguage: typeof import('./script').detectProjectLanguage;
export declare const toJsPath: typeof import('./script').toJsPath;
export declare const buildLazyGlobalDtsOutput: typeof import('./script').buildLazyGlobalDtsOutput;
export declare const buildGlobalDtsOutput: typeof import('./script').buildGlobalDtsOutput;
export declare const buildGlobalJsOutput: typeof import('./script').buildGlobalJsOutput;
export declare const buildGlobalDts: typeof import('./script').buildGlobalDts;
export declare const readPreviousExports: typeof import('./script').readPreviousExports;
export declare const createTsProgram: typeof import('./script').createTsProgram;
export declare const analyzeFiles: typeof import('./script').analyzeFiles;
export declare const findNameCollisions: typeof import('./script').findNameCollisions;
export declare const buildDepGraph: typeof import('./script').buildDepGraph;
export declare const detectCycles: typeof import('./script').detectCycles;
export declare const topoSort: typeof import('./script').topoSort;
export declare const buildLazyDtsOutput: typeof import('./script').buildLazyDtsOutput;
export declare const buildDtsOutput: typeof import('./script').buildDtsOutput;
export declare const buildJsOutput: typeof import('./script').buildJsOutput;
export declare const parseBarrelExports: typeof import('./script').parseBarrelExports;
export declare const DEFAULT_SKIP_PATTERNS: typeof import('./utils').DEFAULT_SKIP_PATTERNS;
export declare const DEFAULT_MODULE_FILE_PATTERN: typeof import('./utils').DEFAULT_MODULE_FILE_PATTERN;
export declare const genExportMap: typeof import('./core/export-map').genExportMap;
export declare const watchSrc: typeof import('./core/watch').watchSrc;
export declare const genAppConfig: typeof import('./core/app-config').genAppConfig;
export declare const genImport: typeof import('./core/import').genImport;
export declare const DEFAULT_MODULE_FILE_PATTERNS: typeof import('./index').DEFAULT_MODULE_FILE_PATTERNS;
export declare const CycleReport: typeof import('./index').CycleReport;
export declare const Edge: typeof import('./index').Edge;
export declare const EdgeKind: typeof import('./index').EdgeKind;
export declare const EagerVia: typeof import('./index').EagerVia;
export declare const ModuleGraph: typeof import('./index').ModuleGraph;
export declare const Scc: typeof import('./index').Scc;
export declare const SccResult: typeof import('./index').SccResult;
export declare const BarrelAnalysis: typeof import('./index').BarrelAnalysis;
export declare const BarrelSafety: typeof import('./index').BarrelSafety;
export declare const Diagnostic: typeof import('./index').Diagnostic;
export declare const DiagnosticCode: typeof import('./index').DiagnosticCode;
export declare const DiagnosticSeverity: typeof import('./index').DiagnosticSeverity;
export declare const StrictMode: typeof import('./index').StrictMode;

Object.defineProperty(exports, 'isEager', { get() { return require('./analysis/scan').isEager }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'strongerVia', { get() { return require('./analysis/scan').strongerVia }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'classifyReference', { get() { return require('./analysis/scan').classifyReference }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'strongerKind', { get() { return require('./analysis/scan').strongerKind }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'scanFile', { get() { return require('./analysis/scan').scanFile }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'createCanonicalizer', { get() { return require('./analysis/graph').createCanonicalizer }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'buildModuleGraph', { get() { return require('./analysis/graph').buildModuleGraph }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'contractBarrel', { get() { return require('./analysis/graph').contractBarrel }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'withBarrelExports', { get() { return require('./analysis/graph').withBarrelExports }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'consumersOf', { get() { return require('./analysis/graph').consumersOf }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'INIT_EDGE_KINDS', { get() { return require('./analysis/graph').INIT_EDGE_KINDS }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'tarjanScc', { get() { return require('./analysis/scc').tarjanScc }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'topoOrder', { get() { return require('./analysis/scc').topoOrder }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'cyclicSccs', { get() { return require('./analysis/scc').cyclicSccs }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'shortestCycle', { get() { return require('./analysis/scc').shortestCycle }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'cycleEdges', { get() { return require('./analysis/scc').cycleEdges }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'condensation', { get() { return require('./analysis/scc').condensation }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'buildRuntimeGraph', { get() { return require('./analysis/barrel').buildRuntimeGraph }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'analyzeBarrel', { get() { return require('./analysis/barrel').analyzeBarrel }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'analyzeBarrelGraph', { get() { return require('./analysis/barrel').analyzeBarrelGraph }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'selectSafeExports', { get() { return require('./analysis/barrel').selectSafeExports }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'describeEagerEdge', { get() { return require('./analysis/barrel').describeEagerEdge }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'explainVia', { get() { return require('./analysis/diagnostics').explainVia }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'collectCycleDiagnostics', { get() { return require('./analysis/diagnostics').collectCycleDiagnostics }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'collectBarrelDiagnostics', { get() { return require('./analysis/diagnostics').collectBarrelDiagnostics }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'countBySeverity', { get() { return require('./analysis/diagnostics').countBySeverity }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'formatDiagnostics', { get() { return require('./analysis/diagnostics').formatDiagnostics }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'SEVERITY_BY_CODE', { get() { return require('./analysis/diagnostics').SEVERITY_BY_CODE }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'walk', { get() { return require('./script').walk }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'detectModuleType', { get() { return require('./script').detectModuleType }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'detectProjectLanguage', { get() { return require('./script').detectProjectLanguage }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'toJsPath', { get() { return require('./script').toJsPath }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'buildLazyGlobalDtsOutput', { get() { return require('./script').buildLazyGlobalDtsOutput }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'buildGlobalDtsOutput', { get() { return require('./script').buildGlobalDtsOutput }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'buildGlobalJsOutput', { get() { return require('./script').buildGlobalJsOutput }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'buildGlobalDts', { get() { return require('./script').buildGlobalDts }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'readPreviousExports', { get() { return require('./script').readPreviousExports }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'createTsProgram', { get() { return require('./script').createTsProgram }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'analyzeFiles', { get() { return require('./script').analyzeFiles }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'findNameCollisions', { get() { return require('./script').findNameCollisions }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'buildDepGraph', { get() { return require('./script').buildDepGraph }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'detectCycles', { get() { return require('./script').detectCycles }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'topoSort', { get() { return require('./script').topoSort }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'buildLazyDtsOutput', { get() { return require('./script').buildLazyDtsOutput }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'buildDtsOutput', { get() { return require('./script').buildDtsOutput }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'buildJsOutput', { get() { return require('./script').buildJsOutput }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'parseBarrelExports', { get() { return require('./script').parseBarrelExports }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'DEFAULT_SKIP_PATTERNS', { get() { return require('./utils').DEFAULT_SKIP_PATTERNS }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'DEFAULT_MODULE_FILE_PATTERN', { get() { return require('./utils').DEFAULT_MODULE_FILE_PATTERN }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'genExportMap', { get() { return require('./core/export-map').genExportMap }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'watchSrc', { get() { return require('./core/watch').watchSrc }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'genAppConfig', { get() { return require('./core/app-config').genAppConfig }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'genImport', { get() { return require('./core/import').genImport }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'DEFAULT_MODULE_FILE_PATTERNS', { get() { return require('./index').DEFAULT_MODULE_FILE_PATTERNS }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'CycleReport', { get() { return require('./index').CycleReport }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'Edge', { get() { return require('./index').Edge }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'EdgeKind', { get() { return require('./index').EdgeKind }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'EagerVia', { get() { return require('./index').EagerVia }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'ModuleGraph', { get() { return require('./index').ModuleGraph }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'Scc', { get() { return require('./index').Scc }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'SccResult', { get() { return require('./index').SccResult }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'BarrelAnalysis', { get() { return require('./index').BarrelAnalysis }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'BarrelSafety', { get() { return require('./index').BarrelSafety }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'Diagnostic', { get() { return require('./index').Diagnostic }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'DiagnosticCode', { get() { return require('./index').DiagnosticCode }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'DiagnosticSeverity', { get() { return require('./index').DiagnosticSeverity }, enumerable: true, configurable: true });
Object.defineProperty(exports, 'StrictMode', { get() { return require('./index').StrictMode }, enumerable: true, configurable: true });
